openapi: 3.0.0
info:
  title: Secure API Project
  version: 1.0.0
  description: A secure API project with comprehensive testing.
servers:
  - url: http://localhost:3000
paths:
  /api/users:
    get:
      summary: Retrieve a list of users
      responses:
        '200':
          description: A list of users retrieved successfully.
        '500':
          description: Internal server error.
    post:
      summary: Create a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
      responses:
        '201':
          description: User created successfully.
        '400':
          description: Bad request. Name or email missing.
        '500':
          description: Internal server error.
